FormidableLabs/webpack-dashboard

utils/format-modules.js
Before:
After:
Before, it was slightly confusing, because I was quickly scanning the
percentages and didn't know why a module down the list was at 90%,
before realizing it was 90% of its dependent module. Now it should be
more immediately obvious.
Cheers, I already plan on using this by default for all of my projects! :beers:
=> Indent the child modules' size percentage

dashboard/index.js
Fixes padding so status and operation will display
Found the issue is from having both a top and bottom padding of 1
Refs: https://github.com/FormidableLabs/webpack-dashboard/issues/19
=> Fix padding for iTerm

README.md
Took a small amount of digging to learn there wasn't anything wrong with my setup other than Terminal.app in OSX does not support mouse events at all. This PR simply adds a small note to that extent in the 'run' section.
=> Note that scrolling does not work in Terminal.app

utils/format-modules.js
- fixes #38 
- add a `getPosition` method to the `format-modules.js` file
- if module begins with `@` don't strip after first path seperator
=> fix #38 and also show scoped modules

README.md
I'm a Terminal.app user and the mouse stuff works just fine for me. This updates the README note to mention the necessary option (which I think is the default anyway; I don't remember ever messing with it).
=> Update note about Terminal.app

README.md
Clarifies that the port needs to be passed to the DashboardPlugin constructor as well as included in the call to webpack-dashboard if using a custom port number. Fixes #58.
=> Clarify using a custom port

bin/webpack-dashboard.js, package.json, plugin/index.js
Per #72, `json-socket` has issues with multibyte characters in large messages. I already made a pull request to fix the issue upstream, but I'm not optimistic about it being merged.
`socket.io` appears to be much more actively maintained and properly supports the messages `json-socket` was having problems with (and it was mostly a 1:1 replacement).
=> Switch from json-socket to socket.io

package.json
After running `npm install webpack-dashboard@0.1.5` to upgrade from 0.1.4 and starting webpack as usual, I receive the error message 
```
Error: Cannot find module 'socket.io-client'
...
...
at Object.<anonymous> (.../node_modules/webpack-dashboard/plugin/index.js:6:22)
```
After `cd`ing into node_modules/webpack-dashboard/ and running `npm install --save socket.io-client` webpack dashboard works as usual
=> add socket.io-client as dependency

docs/api.md, docs/getting-started.md
This PR adds the basic markdown files that will form the "docs" section of the new webpack-dashboard lander
cc/ @kenwheeler
=> adding markdown files for getting started guide and api docs

dashboard/index.js
After I tried to run webpack-dashboard it immediately crashed with this exception:
```TypeError: Cannot read property 'slice' of null
at /Users/charud/dev/open/node_modules/blessed/lib/program.js:2543:35
at Array.forEach (native)
at Program._attr (/Users/charud/dev/open/node_modules/blessed/lib/program.js:2542:11)
at ScrollableBox.Element._parseTags (/Users/charud/dev/open/node_modules/blessed/lib/widgets/element.js:498:26)
at ScrollableBox.Element.parseContent (/Users/charud/dev/open/node_modules/blessed/lib/widgets/element.js:393:22)
at ScrollableBox.Element.setContent (/Users/charud/dev/open/node_modules/blessed/lib/widgets/element.js:335:8)
at ScrollableBox.Element.insertLine (/Users/charud/dev/open/node_modules/blessed/lib/widgets/element.js:2383:8)
at ScrollableBox.Element.pushLine …
```
=> Filter curly braces from logs

utils/format-modules.js
this will make `webpack-dashboard` working on older version of nodejs.
=> remove es6 syntax, fixes #126

plugin/index.js
It's interesting for compile times.
What about showing millis up to 10 seconds instead if 1?
=> Show millis under Operation

bin/webpack-dashboard.js, plugin/index.js
This pull request is not meant to be merged as-is.
The code is a bit ugly and needs reviewing.
It is however a working implementation.
Now, webpack-dashboard can get the logs directly from Webpack.
Instead of using 2 IPCs (standard output for logs, sockets for everything else) you can now use sockets only.
To use this, just omit the child command. Hence, the usage would be:
```
webpack-dashboard
```
or, for a specific port, say 3001
```
webpack-dasboard --port 3001
```
I needed this for myself, and here's why.
I run webpack in a container. It is much easier for me to simply connect to the socket than it is to redirect the standard output properly. I first tried that but ended up with contrived commands (and loss of color output).
I have a single webpack process that produces two bundles ; …
=> Get log directly from Webpack

plugin/index.js
Inspired by solutions to #149 provided by @nlutterman
=> Respect `stats` options from webpack config in log output

plugin/index.js
Tried the new alpha against https://github.com/andrewngu/sound-redux and it had parse errors (not the first report of these). Turns out that we're trying to parse sourcemaps (oops). Now we don't and everything's peachy!
=> Don't parse sourcemaps!

dashboard/index.js, package.json, plugin/index.js, utils/error-serialization.js, utils/format-modules.js, yarn.lock
Fixed a couple of bugs:
- Error messages for `inspectpack` data were busted (tried to send `Error` objects over the socket lol). Now they're normal!
- Module percentages were in relation to the full bundle's min+gz size, but the combination of all min+gz module sizes !== the bundle's min+gz size (especially when duplicate modules are involved, as `gzip` can effectively compress duplicate strings). Now percentages are in relation to the sum of all module min+gz sizes, and they _actually add up to 100%_ 😆 
- The wrong label got set on problem errors. Now the right one gets set.
=> Fix busted error messages, fix percentages

plugin/index.js
If `DashboardPlugin()` is left in the plugins on a non-watching build an open websocket prevents webpack from exiting on completion. This update will close down the socket if it exists and we aren't in watch mode. 
/cc @kenwheeler
=> Fix for #151: Webpack doesn't exit

package.json, plugin/index.js, yarn.lock
This allows the `sizes` action to emit to the dashboard before the "problem" actions (which take a good bit more time). We lost this "streaming" in #178 because we needed completion semantics to clear up the socket/inspectpack daemon. Now we can emit messages independently _and_ know when they're complete!
This could also open up more granular streaming, e.g. spit out each bundle's size as soon as we know it instead of `Promise.all`ing it.
=> Stream actions with completion to the socket

package-lock.json, package.json, yarn.lock
I have `webpack@3` in my project. After adding `webpack-dashboard@1.0.0-5`, I now have two versions of webpack in my `node_modules` tree. Since `webpack` is already listed as a peer dependency, a specific version should only be added as a devDependency.
Thanks! I'm loving working at NASA with this dashboard! :tada:
=> Move specific webpack version to devDependencies

README.md, package-lock.json, plugin/index.js, utils/format-problems.js, utils/format-versions.js
We have a bug opened in `inspectpack` repo that is really a `webpack-dashboard` issue. Fixes https://github.com/FormidableLabs/inspectpack/issues/45
The `inspectpack` `versions` action detects versions skews in installed packages within a webpack bundle by actually traversing the `node_modules` installed from the "project root" which is basically the directory that contains the operating `package.json`.
Some bespoke webpack configurations change `bundle.context` to something _other_ than a directory that is our "project root". This causes `inspectpack` to rightfully bomb out with a `Error: Unable to find project root package.json` error -- because if you're running `versions` you need to have this accessible.
In `webpack-dashboard`-land, it pays to be a little more permissive, because …
=> Add more project root inference for `versions` (aka `Unable to find project root package.json` issue)

dashboard/index.js
Minor fix to allow boxes to have a `-1` offset to fit all three boxes in one row depending on the sizing of the terminal window.
Depending on the size of the window, the three sizes of `34%`, `34%` and `33%` can cause an overflow. Testing different sizing configurations, `34%-1`, `34%-1` and `33%` had the most consistent results of always showing all three boxes on the same row and it consuming most of the full width.
Tested in both Terminal and iTerm.
Addresses https://github.com/FormidableLabs/webpack-dashboard/issues/174
cc @ryan-roemer @kenwheeler
=> Fixed minimal sizing of the 3 lower boxes

dashboard/index.js
Since we parse and display errors in `setStats(data)` to the log with `this.logText.log(formatOutput(stats))`, the errors from the normal log duplicate the messages with extra output. The simple fix is to not log output when we have errors we parsed and are displaying.
Addresses https://github.com/FormidableLabs/webpack-dashboard/issues/66
**Success**
**Failure**
cc @ryan-roemer @kenwheeler
=> Do not output log when errors are present.

bin/webpack-dashboard.js, dashboard/index.js, plugin/index.js, utils/format-modules.js
• Fix Webpack 3 module reporting. The path names are different so previously we just saw a single entry. Also ensure module reporting still works for Webpack 2.
• Disable analysis with inspectpack when running in minimal mode
• Show better warnings when inspectpack cannot get more data when Webpack is running in production
Addresses #201 #198 
**Production**
**Fixed Webpack 3**
**Webpack 2**
cc @ryan-roemer @kenwheeler
=> Fix WP 3 size reporting, disable inspectpack in minimal

README.md, dashboard/index.js, plugin/index.js
For electron webpack dashboard we want to visually show differences when running in production and be more specific in webpack dashboard. This will be needed for https://github.com/FormidableLabs/electron-webpack-dashboard/issues/33.
Addresses #197 
* See if the `DefinePlugin` exists and safely traverse the object to see if a `production` `NODE_ENV` variable is set
* Report that value once when the webpack process starts (since it cannot change over the lifetime of the running dashboard instance)
cc @kenwheeler @ryan-roemer
=> Added support for node env provide plugin.

.eslintrc, .gitignore, .nycrc, .travis.yml, bin/webpack-dashboard.js, package-lock.json, package.json, test/.eslintrc, test/base.spec.js, test/bin/webpack-dashboard.spec.js, test/dashboard/index.spec.js, test/mocha.opts, test/plugin/index.spec.js, test/setup.js, yarn.lock
* Fixes #205 
* Add the most minimal skeleton tests to import most files and check for rudimentary breakage.
* Make `bin/webpack-dashboard.js` exportable in addition to being a script.
* Follow-on real test ticket at #207 
* Update eslintrc to use `arrow-parens: [error, as-needed]`
/cc @kenwheeler @tptee @carlospaelinck
=> Add basic tests + various infrastructure.

README.md
=> Added OS support section

README.md, plugin/index.js
I work on many projects at same time, to not deal with port issues on them I usually dockerize the servers (a small performance trade-off for the convenience).
The problem is that the best place to run the **webpack-dashboard** server is in my local terminal and the new **electrum-webpack-dashboard** we have no choice...
As a solution, we can add the option to change where the client will connect, in this case, I can expose my host IP to the container, and it will connect the port and provide the socket communication.
In the documentation, I have added the `host` option and a bit of clarification of what is server and what is client in this project. I know many people don't care, but that would save me a lot of time to understand how it works, instead of going to the source code to figure …
=> Feature - Add plugin host option

plugin/index.js
This makes it so the dashboard plugin can be configured without creating the inspectpack daemon.  If the daemon is created in the constructor, the plugin cannot be conditionally applied.  Currently, if the plugin is configured and added as part of a development only config, the process running the production config will never exit.  With the changes here, the plugin can be configured but if it is never applied, the webpack process exits properly.
Fixes #96.
Fixes #125.
=> Wait until apply to create inspectpack daemon

utils/format-assets.js, utils/format-modules.js
this issue can be found in electron based project when using electron API in `renderer`
```
yarn run v1.2.1
$ webpack-dashboard -- node .electron-vue/dev-runner.js
TypeError: Cannot read property 'meta' of undefined
at assets.filter.map.asset (/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/webpack-dashboard/utils/format-assets.js:28:41)
at Array.map (<anonymous>)
at _.flatMap.assets (/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/webpack-dashboard/utils/format-assets.js:24:8)
at l (/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/lodash/lodash.min.js:6:443)
at uu (/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/lodash/lodash.min.js:67:252)
at On.flatMap (/home/wildan/Projects/Sensorfied/f.i.d.e/node_modules/lodash/lodash.min.js:99:101)
at l …
```
=> fix issue when bundle don't have metrics at all

.eslintrc, .eslintrc.json, .gitignore, README.md, bin/webpack-dashboard.js, examples/.eslintrc.json, examples/config/webpack.config.js, examples/duplicates-esm/node_modules/foo/index.js, examples/duplicates-esm/node_modules/foo/package.json, examples/duplicates-esm/node_modules/uses-foo/index.js, examples/duplicates-esm/node_modules/uses-foo/node_modules/foo/index.js, examples/duplicates-esm/node_modules/uses-foo/node_modules/foo/package.json, examples/duplicates-esm/node_modules/uses-foo/package.json, examples/duplicates-esm/package.json, examples/duplicates-esm/src/index.js, examples/simple/package.json, examples/simple/src/index.js, examples/tree-shaking/node_modules/foo/green.js, examples/tree-shaking/node_modules/foo/index.js, examples/tree-shaking/node_modules/foo/package.json, examples/tree-shaking/node_modules/uses-foo/index.js, examples/tree-shaking/node_modules/uses-foo/node_modules/foo/green.js, examples/tree-shaking/node_modules/uses-foo/node_modules/foo/index.js, examples/tree-shaking/node_modules/uses-foo/node_modules/foo/package.json, examples/tree-shaking/node_modules/uses-foo/package.json, examples/tree-shaking/package.json, examples/tree-shaking/src/index.js, package.json, yarn.lock
This PR adds some niceties to make the contributing process for `webpack-dashboard` a bit easier. Specifically, we introduce a `yarn dev` command that allows a user to immediately run one of the example fixtures in `/examples`. The example being run is controlled by `process.env.EXAMPLE`, which can be altered in `package.json`.
I need to give @mhink credit for the implementation idea here. He suggested adding some sort of flag to the CLI to indicate that we want to run the example project. When that flag (supplied as `-e, --example`) gets passed, we spin up a separate child process to run one of the fixtures specified in `/examples` (based on the value of `process.env.EXAMPLE`). This will _only_ work currently if no other command is passed to `webpack-dashboard` and you're running `-e` …
=> Simplify contribution process. Integrate inspectpack fixtures.

.eslintrc.json, .travis.yml, README.md, bin/webpack-dashboard.js, dashboard/index.js, examples/simple/src/index.js, package.json, plugin/index.js, test/.eslintrc, test/.eslintrc.json, test/base.spec.js, test/bin/webpack-dashboard.spec.js, test/dashboard/index.spec.js, test/utils/format-versions.spec.js, utils/format-assets.js, utils/format-duplicates.js, utils/format-modules.js, utils/format-output.js, utils/format-versions.js, yarn.lock
This PR migrates us to using [`neo-blessed`](https://github.com/embark-framework/neo-blessed) 🎉, an actively maintained fork of `blessed`. After doing some experimentation to look at a full rewrite with [`react-blessed`](https://github.com/Yomguithereal/react-blessed) or [`ink`](https://github.com/vadimdemedes/ink/tree/next), I found significant drawbacks to each.
With `react-blessed`, there are some weird behaviors with some of the core styling APIs of `blessed` (for example, using `padding` breaks layout entirely). Moreover, the attributes supplied to JSX nodes in `react-blessed` just desugar to calls to `blessed` anyways, so we don't get any underlying enhancements for what would be a considerable migration.
`ink` isn't really in the same mold as `blessed` and doesn't allow you to …
=> Migrate to using neo-blessed as underlying blessed renderer.

.prettierignore, dashboard/index.js, package.json, yarn.lock
This PR addresses #272, which is based off of https://github.com/FormidableLabs/nodejs-dashboard/pull/93. After doing some digging in the [`neo-blessed` source](https://github.com/embark-framework/neo-blessed/blob/master/lib/widgets/screen.js#L225-L235), it appears that they support sending `SIGINT` as a way to gracefully exit the dashboard process if no other handlers exist for that signal. From all the local testing I've done, this doesn't appear to interfere with any existing dashboard functionality. Would love another person to do a local pull of this branch for final verification, but otherwise I don't see much downside in shipping this. Once merged, I'll release 3.0.1 that also includes some security fixes.
=> #272 Use process.kill with SIGINT to terminate dashboard process.

.gitignore, CHANGELOG.md, bin/webpack-dashboard.js, dashboard/index.js, plugin/index.js
Thanks to great insight by @westbrook-asapp it appears we're sending the full webpack stats object from client (webpack plugin) to server (CLI) when we **only** need the errors and warnings fields. This PR:
- Limits the webpack stats messaged object to just errors and warnings. Fixes #279 
- Add client disconnect / error messages to help analogous issues in the future.
/cc @parkerziegler @westbrook-asapp
Currently can reproduce the bug in #279 as follows:
```sh
$ yarn
$ cross-env EXAMPLE=simple node bin/webpack-dashboard.js -- webpack-cli --config examples/config/webpack.config.js --watch
$ cross-env EXAMPLE=simple TMP_BIG_STATS=true node bin/webpack-dashboard.js -- webpack-cli --config examples/config/webpack.config.js --watch
```
I haven't started at looking at solutions, but we've …
=> BUG: Handle large webpack stats bundles without socket.io client disconnect.

package.json, yarn.lock
Handlebars has a security advisory out for 4.1.1, so yarn/npm audit will complain about ^4.1.0. This is to fix that.
=> Update handlebars dependency to ^4.1.2

bin/webpack-dashboard.js
Closes issue #212 
adds a conditional check for os and sets the `detached` argument of `spawn` to stop additional window from opening.
[https://nodejs.org/api/child_process.html#child_process_options_detached](https://nodejs.org/api/child_process.html#child_process_options_detached)
=> adds a conditional check for os to keep extra windows from opening

dashboard/index.js
When we have more than 5 modules (depends on the name size) we can't select it with mouse anymore.
So I think we can use left/right keys to switch between modules.
=> Add left/right navigation to move between modules

package.json
Add chalk to package.json to fix implicit dependency as this will break in Yarn 2
✅ Closes: #308
=> fix: 🐛 Add chalk to package.json to fix implicit dependency

CHANGELOG.md, bin/webpack-dashboard.js, package.json, plugin/index.js, yarn.lock
Update all production dependencies. After this, only thing left is webpack5 update and refactoring:
```sh
$ yarn outdated
Package     Current Wanted Latest Package Type    URL                                          
webpack     4.46.0  4.46.0 5.16.0 devDependencies https://github.com/webpack/webpack           
webpack-cli 3.3.12  3.3.12 4.4.0  devDependencies https://github.com/webpack/webpack-cli#readme
```
=> Chore: Update prod dependencies.

CHANGELOG.md, dashboard/index.js, examples/duplicates-esm/src/index.js, plugin/index.js
- Ensure a finished compilation state (failed, error, success) isn't overwritten by the ProgressPlugin. Fixes #321 
- Add error status inferred from webpack stats.
=> Bugfix: Ensure status is updated correctly on compilation finishing.

package.json, yarn.lock
My repo using webpack-dashboard has received a [security alert CVE-2020-28502 on xmlhttprequest-ssl vulnerability](https://github.com/advisories/GHSA-h4j5-c7cj-74xg), hence this PR.
=> Bump socket.io version to get rid of vulnerable xmlhttprequest-ssl package

CHANGELOG.md, dashboard/index.js, package.json, plugin/index.js, test/plugin/index.spec.js, yarn.lock
Refactors the plugin internal logic to be a lot simpler. 
- Chore: Refactor internal stats consumption to perform `inspectpack` analysis in the main thread, without using `main` streams. Originally, the `inspectpack` engine did some really heavy CPU stuff (gzipping lots of files), but now the actions are super fast, so I've removed `most` async observables and just switched to straight promises.
- Chore: Refactor internal handler in plugin to always be a wrapped function so that we can't accidentally have asynchronous code call the handler function after it is removed / nulled.
- Bugfix: Add message counting delayed cleanup in plugin to allow messages to drain in Dashboard. The issue seems to be that we hit socket IO disconnect in the plugin before the dashboard actually processes the …
=> Chore: Various plugin refactoring and simplification.

.changeset/config.json, .changeset/plenty-spiders-sip.md, .github/workflows/release.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, package.json, yarn.lock
- Setting up a `release.yml` GitHub Workflow so that we can publish to NPM in an automated fashion.
- Added `changesets` as the tool to control semantic-release versioning for NPM publishing.
- Added the following in order to add Provenance verification badge on [this NPM page](https://www.npmjs.com/package/webpack-dashboard)
```
"publishConfig": {
"provenance": true
}
```
- Added a `NPM_TOKEN` to the settings of this repo.
- Added a `CONTRIBUTING.md` guide
=> GitHub Actions release workflow addition
