FormidableLabs/webpack-dashboard

dashboard/index.js, plugin/index.js, utils/mock-console.js
=> console redirection

README.md
Just fixing the invalid syntax in the code snippets
=> minor README typo fixes

bin/webpack-dashboard.js, dashboard/index.js, package.json, plugin/index.js
- Fixes windows by using cross-spawn, closes #57, #62
- Fixes babel node issue where child processes aren't killed, closes #61
cc @exogen @ryan-roemer Does this seem reasonable?
=> Fixing windows & babel-node

bin/webpack-dashboard.js
this fixes the issues mentioned in #83
=> fix process killing issue on Windows

CONTRIBUTING.md
adding code of conduct to the repo
cc/ @kenwheeler
=> adding contributing file with code of conduct

README.md, bin/webpack-dashboard.js, dashboard/index.js
Helps identification when running multiple webpack processes.
=> Add option to set title of terminal window

plugin/index.js
Add a timer section http://imgur.com/XywNYC5
https://github.com/FormidableLabs/webpack-dashboard/issues/24
=> Add timer section, that shows how much time it took to compile

utils/format-output.js
=> Remove eslint warnings

dashboard/index.js, utils/format-modules.js
=> Showing version alongside name/size/percentage in modules table

package.json
I've removed webpack as a dependency and it appears to be working fine on my project.
- Compiling still happening
- Progress bar still working
- Errors still in log
- Modules, assets table etc.
Edit:
Should probably mention that this fixes #135
=> Removed webpack as a dependency as it is already a peerDependency

.editorconfig, .eslintrc, bin/webpack-dashboard.js, dashboard/index.js, index.js, package.json, plugin/index.js, utils/format-assets.js, utils/format-modules.js, utils/format-output.js, yarn.lock
Depends on/branched from #157 
The diffs in the plugin and dashboard look a little messy since moving them to an ES6 class added a level of indentation ¯\_(ツ)_/¯
=> Add linting and convert to node 4 ES6

README.md
=> Fix header formatting

package-lock.json, package.json, plugin/index.js
This PR enables the dashboard to work in single run mode, and exit cleanly. cc @tptee @ryan-roemer
=> Electron fix

package.json, yarn.lock
This fixes projects that don't transpile and use `uglify-es`!
=> Upgrade inspectpack

.npmignore, LICENSE
=> Add npmignore whitelist, update license.

dashboard/index.js
Added Keyboard Navigation for the main log
Addresses #147 
1. **Page Up** — Scroll to top
2. **Page Down** — Scroll to bottom
3. **Up** — Scroll up one line
4. **Down** — Scroll down one line
cc @kenwheeler @ryan-roemer
=> Added keyboard navigation for main log.

README.md, dashboard/index.js, plugin/index.js, utils/format-assets.js, utils/format-modules.js, utils/inspectpack.js
This PR adds `minified` and `gzip` configuration options that can optionally disable the relatively expensive per-module calculations of each by `inspectpack` under the hood.
- Fixes #227
- Adds `minified` and `gzip` plugin options, both defaulted to `true` so we don't need a semver major bump.
- Adds more README documentation and explanations about CPU intensive workloads and the `inspectpack` cache.
/cc @kenwheeler @tptee 
I took a previous project opened for bug diagnosis with a reasonably-sized app, and compared outputs, stats and execution times:
```
┌──Modules───────────────────────────────────────────────────────────────────────────────────────────┐┌──Assets────────────────────────────────────────────────────────────────────────────────────────────┐
│ …
```
=> Feature: Enable opt-out of minified, gzip calculations.

utils/format-assets.js
Make stats object parsing more permissive.
- Part of #231
- Introduced in #230
/cc @kenwheeler @jodriscoll
=> Bug: Allow better fallback for real metrics.

dashboard/index.js, test/dashboard/index.spec.js, test/plugin/index.spec.js, test/utils/format-assets.spec.js, test/utils/format-modules.spec.js, test/utils/format-output.spec.js, utils/format-assets.js, utils/format-modules.js, utils/format-output.js
@ryan-roemer @parkerziegler The test are testing some default and optional settings but I wanted to go back test the utils file since it seems to be the base fo a lot of other functionality. Also, wanted to give you some chance to see where I have been going with testing and see if it is a good direction to be heading in.  My search in how to test cli has not been as fruitful as I would hope but I think it can be done. I think the hardest part I am having is knowing what the data structure of arguments look like as they are pass to functions. In turn making hard to make mock data to test functions. I am not that familiar with mocha and mocking data as well. So in reviewing this PR any advice or ideas on how to tackle the following would be extremely useful...
- How to mock things in …
=> [WIP] add unit test for dashboard/index.js and plugin/index.js

package.json, yarn.lock
This is what I get in my project
```
yarn audit
yarn audit v1.13.0
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.13                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @operational/scripts                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ …
```
=> Update dependencies to fix security issues

.prettierrc, .travis.yml, CHANGELOG.md, README.md, appveyor.yml, package.json, test/utils/format-modules.spec.js, utils/format-modules.js
- Add more badges!!!
- Add windows to CI run via appveyor.
- Add node11
- Switch pkg.json quotes to double for win.
We uncovered some minor stuff, but pretty easy!
I originally tried this on Travis windows, but it's **so, so slow** 🐢 
Lets compare those times to appveyor 😂
=> CI: Add windows.

.mocharc.yml, .prettierrc, package.json, test/mocha.opts, test/plugin/index.spec.js, test/utils/format-versions.spec.js, utils/format-duplicates.js, utils/format-versions.js, yarn.lock
Updates all `devDependencies` except for webpack which we're going to tackle in #316
=> Chore: Update devDependencies.

CHANGELOG.md, README.md, bin/webpack-dashboard.js, examples/config/webpack.config.js, package.json, plugin/index.js, utils/format-output.js, yarn.lock
- Add webpack5 support. Fixes #316 
- Bugfix: Webpack 5 warning message conflict. Fixes #314
- Fix bugs in updated `commander` integration.
=> Chore: webpack5 support.

README.md, docs/getting-started.md
- Update docs with new modern webpack integration link for express/wds/etc. Closes #312
=> Docs: Update for webpack5

ISSUE_TEMPLATE.md
- Fixed horizontal rules
- Altered the headings to be more legible
=> Cleaned up the issue template

README.md
Very small PR that updates the images in the README to use https rather than http. These images were causing some netlify checks to fail downstream on formidable.com
=> Update readme image urls
